#javac -d bin -cp bin:libs/* src/louis/driver/dookious/utils/*.java
#javac -d bin -cp bin:libs/* src/louis/driver/dookious/dmove/SurfHitsBufferBase.java
#javac -d bin -cp bin:libs/* src/louis/driver/dookious/dmove/SurfHighBufferBase.java
#javac -d bin -cp bin:libs/* src/louis/driver/dookious/dmove/SurfLowBufferBase.java
#javac -d bin -cp bin:libs/* src/louis/driver/dookious/dmove/SurfNonFiringBufferBase.java
#javac -d bin -cp bin:libs/* src/louis/driver/dookious/dmove/buffers/*.java
#javac -d bin -cp bin:libs/* src/louis/driver/dookious/dmove/SurfHighBufferSet.java
#javac -d bin -cp bin:libs/* src/louis/driver/dookious/dmove/SurfLowBufferSet.java
#javac -d bin -cp bin:libs/* src/louis/driver/dookious/dmove/SurfNonFiringBufferSet.java
#javac -d bin -cp bin:libs/* src/louis/driver/dookious/dmove/DookiCape.java
#javac -d bin -cp bin:libs/* src/louis/driver/dookious/dmove/*.java
#javac -d bin -cp bin:libs/* src/louis/driver/dookious/dgun/*.java
javac -d bin -cp bin:libs/* src/louis/driver/*.java
javac -d bin -cp bin:libs/* src/louis/*.java
